//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdrianoAutoApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdrianoAutoApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.0.0.1 lmlicenses.wip4.adobe.com
        ///127.0.0.1 lm.licenses.adobe.com
        ///127.0.0.1 activate.adobe.com
        ///127.0.0.1 practivate.adobe.com
        ///127.0.0.1 ereg.adobe.com
        ///127.0.0.1 activate.wip3.adobe.com
        ///127.0.0.1 3dns-3.adobe.com
        ///127.0.0.1 3dns-2.adobe.com
        ///127.0.0.1 adobe-dns.adobe.com
        ///127.0.0.1 adobe-dns-2.adobe.com
        ///127.0.0.1 adobe-dns-3.adobe.com
        ///127.0.0.1 ereg.wip3.adobe.com
        ///127.0.0.1 activate-sea.adobe.com
        ///127.0.0.1 wwis-dubc1-vip60.adobe.com
        ///127.0.0.1 activate-sjc0.adobe.com
        ///127.0.0.1 hl2rcv.adobe.com
        ///127.0.0.1 na2m-p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Adobe {
            get {
                return ResourceManager.GetString("Adobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.0.0.1 mc.corel.com
        ///127.0.0.1 apps.corel.com
        ///127.0.0.1 origin-mc.corel.com
        ///127.0.0.1 iws.corel.com
        ///127.0.0.1 compute-1.amazonaws.com  
        ///127.0.0.1 ipm.corel.com  
        ///127.0.0.1 dev1.ipm.corel.public.corel.net.
        /// </summary>
        internal static string CorelDraw {
            get {
                return ResourceManager.GetString("CorelDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.0.0.1 backup.lumion3d.net
        ///127.0.0.1 license.lumiontech.net.
        /// </summary>
        internal static string Lumion {
            get {
                return ResourceManager.GetString("Lumion", resourceCulture);
            }
        }
    }
}
